steps:
- id  : build API microservice
  waitFor : ['-']
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/s4a-shared-docker-registry/node-gke-microservice-api', 'src/api']
- id  : build FRUIT microservice
  waitFor : ['-']
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/s4a-shared-docker-registry/node-gke-microservice-fruit', 'src/fruitService']
- id  : build GREETER microservice
  waitFor : ['-']
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/s4a-shared-docker-registry/node-gke-microservice-greeter', 'src/greeterService']

- id  : Create release
  waitFor : ['build API microservice', 'build FRUIT microservice', 'build GREETER microservice']
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - >
    gcloud deploy releases create release-$BUILD_ID
    --delivery-pipeline=hello-world-app
    --region=europe-west1
    --source=./

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/s4a-shared-docker-registry/node-gke-microservice-api'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/s4a-shared-docker-registry/node-gke-microservice-fruit'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/s4a-shared-docker-registry/node-gke-microservice-greeter'
