---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: hello-world-app
description: Hello World Deployment Pipeline
serialPipeline:
  stages:
  # - targetId: build
  #   profiles:
  #    - cloudbuild
  - targetId: staging
    profiles:
     - staging
  - targetId: production
    profiles:
     - production
# ---
# apiVersion: deploy.cloud.google.com/v1beta1
# kind: Target
# metadata:
#   name: build
# description: Build images
# gke:
#   cluster: projects/test-ahn-dev/locations/europe-west1/clusters/skaffold-gke-poc
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: staging
description: Staging Environment
gke:
  cluster: projects/test-ahn-dev/locations/europe-west1/clusters/skaffold-gke-poc
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: production
description: Production Environment
requireApproval: true
gke:
  cluster: projects/test-ahn-dev/locations/europe-west1/clusters/skaffold-gke-poc
