steps:
# - name: 'gcr.io/k8s-skaffold/pack'
#   entrypoint: 'pack'
#   args: ['build', '--builder=gcr.io/buildpacks/builder', '--publish', 'europe-west1-docker.pkg.dev/$PROJECT_ID/s4a-shared-docker-registry/hello-world:$SHORT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - >
    gcloud deploy releases create release-$BUILD_ID
    --delivery-pipeline=hello-world-app
    --region=europe-west1
    --source=./
