apiVersion: skaffold/v2beta16
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - context: src/api
      image: europe-west1-docker.pkg.dev/$PROJECT_ID/s4a-shared-docker-registry/node-gke-microservice-api
    - context: src/fruitService
      image: europe-west1-docker.pkg.dev/$PROJECT_ID/s4a-shared-docker-registry/node-gke-microservice-fruit
    - context: src/greeterService
      image: europe-west1-docker.pkg.dev/$PROJECT_ID/s4a-shared-docker-registry/node-gke-microservice-greeter

profiles:
  - name: cloudbuild
    build:
      googleCloudBuild: {}

  - name: staging
    deploy:
      kubectl:
        manifests:
          - kubernetes-manifests/**
        defaultNamespace: staging

  - name: production
    deploy:
      kubectl:
        manifests:
          - kubernetes-manifests/**
        defaultNamespace: production
