apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: europe-west1-docker.pkg.dev/test-ahn-dev/s4a-shared-docker-registry/node-gke-microservice-api
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
