apiVersion: v1
kind: Service
metadata:
  labels:
    app: greeter
  name: greeter
spec:
  type: NodePort
  selector:
    app: greeter
  ports:
    - name: greeter-port
      port: 3000
      targetPort: 3000
